version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
   configuration: doc/configuration.py

python:
   install:
   - requirements: doc/requirements.txt
   - requirements: requirements.txt
