DROPDOWN_SELECTOR_OPTIONS_XPATH = "//select[@id='options']"

DROPDOWN_SELECTOR_OPTION_1_XPATH = f"{DROPDOWN_SELECTOR_OPTIONS_XPATH}/option[@value='option1']"

DROPDOWN_SELECTOR_OPTION_2_XPATH = f"{DROPDOWN_SELECTOR_OPTIONS_XPATH}/option[@value='option2']"

DROPDOWN_SELECTOR_OPTION_3_XPATH = f"{DROPDOWN_SELECTOR_OPTIONS_XPATH}/option[@value='option3']"

DROPDOWN_SELECTOR_OPTION_4_XPATH = f"{DROPDOWN_SELECTOR_OPTIONS_XPATH}/option[@value='option4']"
