from _mock_data.xpath.mini_site.feature_1 import MINI_SITE_FEATURE_1_IMAGE_1_XPATH

MINI_SITE_FEATURE_2_IMAGE_1_XPATH = MINI_SITE_FEATURE_1_IMAGE_1_XPATH

MINI_SITE_FEATURE_2_IMAGE_2_XPATH = "//*[@id='main']/img[2]"
