from _mock_data.xpath.mini_site.homepage import MINI_SITE_HOMEPAGE_HEADLINE_H1_XPATH

MINI_SITE_FEATURE_1_HEADLINE_H1_XPATH = MINI_SITE_HOMEPAGE_HEADLINE_H1_XPATH

MINI_SITE_FEATURE_1_IMAGE_1_XPATH = "//*[@id='main']/img[1]"
